### ISSUE TITLE
"java.lang.IllegalStateException" on 1.16.5

### ISSUE THREAD

**Issue by Morilli** [bafomdad/uniquecrops#44]
Downloaded the (currently) most recent version `uniquecrops-0.1.36` for 1.16.5 and am getting `java.lang.IllegalStateException: Tag forge:ingots/gold used before it was bound` at the end of the game startup (before the actual main screen appears).

No idea whether this happens on 1.12.2 or whether other installed mods affect this, all I know is that removing this mod here resolves that issue. Note though that I do have a lot of other mods in use.

Full output from the crash log:
```
java.lang.IllegalStateException: Tag forge:ingots/gold used before it was bound
	at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:131) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.tags.TagRegistry$NamedTag.func_230235_a_(TagRegistry.java:142) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.item.Item.func_206844_a(Item.java:343) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothitemench,xf:fml:forge:crossbows.8,pl:mixin:APP:structure_gel.mixins.json:ItemMixin,pl:mixin:APP:assets/uniquecrops/uniquecrops.mixins.json:MixinItemFood,pl:mixin:APP:abnormals_core.mixins.json:ItemInvokerMixin,pl:mixin:A}
	at com.bafomdad.uniquecrops.items.curios.EmblemIronStomach.containsTag(EmblemIronStomach.java:31) ~[?:0.1.36-1.16.5] {re:mixin,re:classloading}
	at net.minecraft.item.Item.handler$zof000$getFood(Item.java:1042) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothitemench,xf:fml:forge:crossbows.8,pl:mixin:APP:structure_gel.mixins.json:ItemMixin,pl:mixin:APP:assets/uniquecrops/uniquecrops.mixins.json:MixinItemFood,pl:mixin:APP:abnormals_core.mixins.json:ItemInvokerMixin,pl:mixin:A}
	at net.minecraft.item.Item.func_219967_s(Item.java) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothitemench,xf:fml:forge:crossbows.8,pl:mixin:APP:structure_gel.mixins.json:ItemMixin,pl:mixin:APP:assets/uniquecrops/uniquecrops.mixins.json:MixinItemFood,pl:mixin:APP:abnormals_core.mixins.json:ItemInvokerMixin,pl:mixin:A}
	at slimeknights.mantle.item.EdibleItem.func_77624_a(EdibleItem.java:42) ~[?:1.16.5-1.6.115] {re:classloading}
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:578) ~[?:?] {re:mixin,re:classloading,xf:fml:placebo:placeboitemusehook,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,pl:mixin:APP:performant.mixins.json:item.ItemStackMixin,pl:mixin:APP:origins.mixins.json:ItemStackMixin,pl:mixin:APP:losttrinkets.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_213251_b(Minecraft.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$39640/1151599191.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.client.util.SearchTreeReloadable.func_217872_a(SourceFile:48) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$createSearchTrees$10(Minecraft.java:660) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$39785/240259989.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:659) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:476) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.2.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/1307119702.call(Unknown Source) [forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
```

**Comment by Morilli** [comment]
I guess this is fixed in 0.1.39 now.
